spring:
  application:
    name: inventory-service
  config:
    import:
      - optional:classpath:application-kafka.yml
      - optional:classpath:application-ecommerce-kafka.yml
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/inventory
    username: ${POSTGRES_USER:ecommerce}
    password: ${POSTGRES_PASSWORD:ecommerce}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    consumer:
      group-id: ${platform.kafka.group-id-prefix}inventory-service

platform:
  kafka:
    group-instance-id: ${HOSTNAME:inventory-service-1}

server:
  port: ${SERVER_PORT:8083}
